[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

fs_permissions = [
    { access = "read", path = "./deployed_addresses_90101.json" },
    { access = "write", path = "./deployed_addresses_90101.json" },
    { access = "read", path = "./deployed_addresses_11155111.json" },
    { access = "write", path = "./deployed_addresses_11155111.json" }
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# [rpc_endpoints]
# op = "${op}"
# mainnet = "${mainnet}"
# sepolia = "${sepolia}"
# roothash = "${roothash}"
